import React, { useEffect, useMemo, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { Calculator, FileText, Pencil, Plus, Save, Ship, Trash2, Upload, X } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useVessels, Vessel } from '@/hooks/useVessels';
import { useSetupCompanies } from '@/hooks/useSetupCompanies';
import { useClassificationSocieties, useFlagStates } from '@/hooks/useSetupClassification';
import { useCurrencies } from '@/hooks/useSetupCrewConfig';
import { useSetupVesselTypes, useSetupHullMaterials, useSetupHullCoatings, useSetupPropulsionTypes, useSetupFuelTypes, useSetupTradingAreas, useSetupEngineMakers, useSetupEngineModels, useSetupShipyards, useSetupPorts } from '@/hooks/useSetupVesselMasterData';
import { useSetupVesselStatus, useSetupOwnershipModes, useSetupRegularities, useSetupRegularityApplicability } from '@/hooks/useVesselUpgradeSetup';
import { useOrganization } from '@/hooks/useOrganization';
import { useToast } from '@/hooks/use-toast';

const EMPTY = { name:'',imo_number:'',call_sign:'',mmsi_number:'',official_number:'',vessel_type:'',flag_state:'',port_of_registry:'',gross_tonnage:'',net_tonnage:'',deadweight:'',year_built:'',classification_society:'',class_number:'',status:'',length_overall:'',beam:'',depth:'',draft:'',engine_make:'',engine_model:'',engine_power:'',propulsion_type:'',max_speed:'',service_speed:'',fuel_consumption:'',fuel_type:'',lifeboats:'',liferafts:'',crew_capacity:'',passenger_capacity:'',cargo_capacity:'',trading_area:'',hull_material:'',hull_coating:'',keel_laid_date:'',delivery_date:'',last_drydock_date:'',next_drydock_date:'',previous_yard:'',remaining_tasks:'',painting_details:'',navigation_equipment:'',accommodations_pax:'',owner_company_id:'',operator_company_id:'',technical_manager_id:'',ism_manager_id:'',notes:'',operational_notes:'',operational_status:'',cabin_count:'',ownership_mode_id:'',vessel_status_id:'',vessel_type_id:'',propulsion_type_id:'',fuel_type_id:'',trading_area_id:'',hull_material_id:'',hull_coating_id:'',port_of_registry_id:'',additional_unmapped_specifications:'',vessel_brochure:'' } as Record<string, any>;
const COST_FIELDS=['crew_manning_daily_cost','accommodation_daily_cost','breakfast_daily_cost','lunch_daily_cost','dinner_daily_cost','snacks_daily_cost','fresh_water_daily_cost','lubricants_daily_cost','consumables_daily_cost','maintenance_daily_cost','repairs_daily_cost','spare_parts_daily_cost','insurance_daily_cost','technical_management_daily_cost','regulatory_certification_daily_cost','communications_daily_cost','waste_sewage_daily_cost','other_daily_operating_cost'];
const label=(v:string)=>v.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const n=(v:any)=>v===''||v==null?null:Number(v);

function Field({name,form,set,type='text'}:{name:string;form:any;set:(k:string,v:any)=>void;type?:string}){return <div className="space-y-1.5"><Label>{label(name)}</Label><Input type={type} value={form[name]??''} onChange={e=>set(name,e.target.value)}/></div>}
function Pick({name,title,form,set,options}:{name:string;title:string;form:any;set:(k:string,v:any)=>void;options:{value:string;label:string}[]}){return <div className="space-y-1.5"><Label>{title}</Label><Select value={form[name]||undefined} onValueChange={v=>set(name,v)}><SelectTrigger><SelectValue placeholder={`Select ${title.toLowerCase()}`}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>}

export default function VesselManagementV2(){
 const {vessels,loading,addVessel,updateVessel,deleteVessel,uploadVesselAsset,getVesselAssetUrl,refetch}=useVessels(); const {orgId}=useOrganization(); const {toast}=useToast();
 const {companies}=useSetupCompanies(); const {societies}=useClassificationSocieties(); const {flagStates}=useFlagStates(); const {currencies}=useCurrencies();
 const types=useSetupVesselTypes().items, hulls=useSetupHullMaterials().items, coatings=useSetupHullCoatings().hullCoatings, props=useSetupPropulsionTypes().items, fuels=useSetupFuelTypes().items, areas=useSetupTradingAreas().items, makers=useSetupEngineMakers().items, models=useSetupEngineModels().items, yards=useSetupShipyards().shipyards, ports=useSetupPorts().ports;
 const statuses=useSetupVesselStatus().items, modes=useSetupOwnershipModes().items, regs=useSetupRegularities().items, applicability=useSetupRegularityApplicability().items;
 const [form,setFormState]=useState({...EMPTY}); const [editing,setEditing]=useState<Vessel|null>(null); const [open,setOpen]=useState(false); const [tab,setTab]=useState('general'); const [search,setSearch]=useState(''); const [saving,setSaving]=useState(false);
 const [financial,setFinancial]=useState<any>({minimum_daily_hire_rate:0,currency_code:'USD',minimum_charter_period_days:null,notes:null,...Object.fromEntries(COST_FIELDS.map(k=>[k,0]))}); const [equipment,setEquipment]=useState<any[]>([]); const [otherCosts,setOtherCosts]=useState<any[]>([]); const [regularityRows,setRegularityRows]=useState<any[]>([]);
 const set=(k:string,v:any)=>setFormState(p=>({...p,[k]:v})); const options=(xs:any[],key='id',name='name')=>xs.map(x=>({value:String(x[key]),label:String(x[name]??x[key])})); const roles=(r:string)=>companies.filter(c=>Boolean((c as any)[r])).map(c=>({value:c.id,label:c.name}));
 const openVessel=async(v:Vessel)=>{setEditing(v);setFormState({...EMPTY,...Object.fromEntries(Object.keys(EMPTY).filter(k=>(v as any)[k]!==undefined).map(k=>[k,(v as any)[k]??'']))});setOpen(true);setTab('general');const {data}=await (supabase as any).from('vessels').select('ownership_mode_id,vessel_status_id,vessel_type_id,propulsion_type_id,fuel_type_id,trading_area_id,hull_material_id,hull_coating_id,port_of_registry_id,operational_notes,operational_status,cabin_count,additional_unmapped_specifications').eq('id',v.id).single();if(data)setFormState(p=>({...p,...data}));
   const [fb,eq,oc,rr]=await Promise.all([supabase.from('vessel_financial_baseline').select('*').eq('vessel_id',v.id).maybeSingle(),supabase.from('vessel_equipment_costs').select('*').eq('vessel_id',v.id).order('sort_order'),supabase.from('vessel_financial_daily_costs').select('*').eq('vessel_id',v.id).order('sort_order'),supabase.from('vessel_regularities').select('*').eq('vessel_id',v.id).order('created_at')]);if(fb.data)setFinancial(fb.data);setEquipment(eq.data||[]);setOtherCosts(oc.data||[]);setRegularityRows(rr.data||[]);
 };
 const newVessel=()=>{setEditing(null);setFormState({...EMPTY});setFinancial({minimum_daily_hire_rate:0,currency_code:(currencies[0] as any)?.currency_code||'USD',minimum_charter_period_days:null,notes:null,...Object.fromEntries(COST_FIELDS.map(k=>[k,0]))});setEquipment([]);setOtherCosts([]);setRegularityRows([]);setOpen(true);setTab('general')};
 const corePayload=()=>{const p={...form};['gross_tonnage','net_tonnage','deadweight','year_built','length_overall','beam','depth','draft','engine_power','max_speed','service_speed','fuel_consumption','lifeboats','liferafts','crew_capacity','passenger_capacity','cargo_capacity'].forEach(k=>p[k]=n(p[k]));return p};
 const save=async()=>{if(!form.name?.trim()){toast({title:'Vessel name is required',variant:'destructive'});return}setSaving(true);try{let id=editing?.id;const payload=corePayload();['ownership_mode_id','vessel_status_id','vessel_type_id','propulsion_type_id','fuel_type_id','trading_area_id','hull_material_id','hull_coating_id','port_of_registry_id','operational_notes','operational_status','cabin_count','additional_unmapped_specifications'].forEach(k=>delete payload[k]);if(!id){const r:any=await addVessel(payload);if(r.error)throw r.error;id=r.data.id}else{const r:any=await updateVessel(id,payload);if(r.error)throw r.error}const {error}=await (supabase as any).from('vessels').update({ownership_mode_id:form.ownership_mode_id||null,vessel_status_id:form.vessel_status_id||null,vessel_type_id:form.vessel_type_id||null,propulsion_type_id:form.propulsion_type_id||null,fuel_type_id:form.fuel_type_id||null,trading_area_id:form.trading_area_id||null,hull_material_id:form.hull_material_id||null,hull_coating_id:form.hull_coating_id||null,port_of_registry_id:form.port_of_registry_id||null,operational_notes:form.operational_notes||null,operational_status:form.operational_status||null,cabin_count:n(form.cabin_count),additional_unmapped_specifications:form.additional_unmapped_specifications||null}).eq('id',id).eq('org_id',orgId);if(error)throw error;
   await (supabase as any).from('vessel_financial_baseline').upsert({...financial,vessel_id:id,org_id:orgId},{onConflict:'vessel_id'});await (supabase as any).from('vessel_equipment_costs').delete().eq('vessel_id',id);await (supabase as any).from('vessel_financial_daily_costs').delete().eq('vessel_id',id);if(equipment.length)await (supabase as any).from('vessel_equipment_costs').insert(equipment.map((x,i)=>({...x,vessel_id:id,org_id:orgId,sort_order:i})));if(otherCosts.length)await (supabase as any).from('vessel_financial_daily_costs').insert(otherCosts.map((x,i)=>({...x,vessel_id:id,org_id:orgId,sort_order:i})));
   await (supabase as any).from('vessel_regularities').delete().eq('vessel_id',id);if(regularityRows.length)await (supabase as any).from('vessel_regularities').insert(regularityRows.filter(x=>x.regularity_id&&x.applicability_status_id).map(x=>({...x,vessel_id:id,org_id:orgId,id:undefined})));
   toast({title:'Vessel saved successfully'});await refetch();setOpen(false)}catch(e:any){toast({title:'Save failed',description:e.message,variant:'destructive'})}finally{setSaving(false)}};
 const totalDaily=useMemo(()=>COST_FIELDS.reduce((s,k)=>s+Number(financial[k]||0),0)+equipment.reduce((s,x)=>s+Number(x.daily_cost||0),0)+otherCosts.reduce((s,x)=>s+Number(x.daily_cost||0),0),[financial,equipment,otherCosts]);
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const path=await uploadVesselAsset(file,editing?.id||'new_vessel');if(path){const url=getVesselAssetUrl(path);set('vessel_brochure',url);toast({title:'Document uploaded'})}};
 const smartFill=async()=>{if(!form.vessel_brochure)return;try{const m=form.vessel_brochure.match(/\/storage\/v1\/object\/(?:public|sign|authenticated)\/([^/]+)\/(.+?)(?:\?.*)?$/);const {data,error}=await supabase.functions.invoke('analyze-image',{body:{fileUrl:form.vessel_brochure,storageBucket:m?.[1],storagePath:m?.[2]?decodeURIComponent(m[2]):undefined,contentType:'application/pdf',org_id:orgId}});if(error)throw error;if(!data?.success)throw new Error(data?.error||'AI extraction failed');setFormState(p=>({...p,...data.data,additional_unmapped_specifications:data.data?.additional_unmapped_specifications||data.data?.notes||p.additional_unmapped_specifications||''}));toast({title:'AI extraction completed'})}catch(e:any){toast({title:'AI extraction failed',description:e.message,variant:'destructive'})}};
 const pdf=async()=>{const {jsPDF}=await import('jspdf');const d=new jsPDF();d.setFontSize(18);d.text(`Vessel Profile — ${form.name||'Vessel'}`,15,20);d.setFontSize(10);['imo_number','vessel_type','flag_state','gross_tonnage','deadweight','operational_status'].forEach((k,i)=>d.text(`${label(k)}: ${form[k]||'—'}`,15,35+i*7));d.text(`Total Daily Operating Cost: ${totalDaily.toLocaleString()} ${financial.currency_code||''}`,15,85);d.save(`${(form.name||'vessel').replace(/\s+/g,'_')}_profile.pdf`)};
 const filtered=vessels.filter(v=>`${v.name} ${v.imo_number||''}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="space-y-6"><div className="flex justify-between items-center"><div><h2 className="text-2xl font-black flex gap-2 items-center"><Ship className="h-7 w-7 text-primary"/>Vessel Management</h2><p className="text-sm text-muted-foreground">Master vessel record, operational condition, baseline cost and regularity.</p></div><Button onClick={newVessel}><Plus className="mr-2 h-4 w-4"/>Add Vessel</Button></div><Input placeholder="Search vessel / IMO..." value={search} onChange={e=>setSearch(e.target.value)}/><Card><CardContent className="p-0"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-4 text-left">Vessel</th><th className="p-4 text-left">IMO</th><th className="p-4 text-left">Type</th><th className="p-4 text-left">Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="p-8 text-center">Loading…</td></tr>:filtered.map(v=><tr className="border-b" key={v.id}><td className="p-4 font-semibold">{v.name}</td><td className="p-4">{v.imo_number||'—'}</td><td className="p-4">{v.vessel_type||'—'}</td><td className="p-4"><Badge variant="outline">{v.status||'—'}</Badge></td><td className="p-4 text-right"><Button size="icon" variant="ghost" onClick={()=>openVessel(v)}><Pencil className="h-4 w-4"/></Button><Button size="icon" variant="ghost" onClick={()=>deleteVessel(v.id)}><Trash2 className="h-4 w-4"/></Button></td></tr>)}</tbody></table></CardContent></Card>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-6xl max-h-[92vh] overflow-y-auto"><DialogHeader><DialogTitle className="flex justify-between items-center"><span>{editing?'Edit Vessel':'New Vessel'}</span><div className="flex gap-2"><Button variant="outline" onClick={pdf}><FileText className="mr-2 h-4 w-4"/>PDF</Button><Button onClick={save} disabled={saving}><Save className="mr-2 h-4 w-4"/>{saving?'Saving…':'Save'}</Button></div></DialogTitle></DialogHeader>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="grid grid-cols-3 lg:grid-cols-9 h-auto"><TabsTrigger value="general">General</TabsTrigger><TabsTrigger value="management">Management</TabsTrigger><TabsTrigger value="technical">Technical</TabsTrigger><TabsTrigger value="operational">Operational</TabsTrigger><TabsTrigger value="financial">Financial</TabsTrigger><TabsTrigger value="regularity">Compliance</TabsTrigger><TabsTrigger value="maintenance">Maintenance</TabsTrigger><TabsTrigger value="media">Media</TabsTrigger><TabsTrigger value="additional">Additional</TabsTrigger></TabsList>
 <TabsContent value="general" className="grid md:grid-cols-3 gap-4 mt-5">{['name','imo_number','call_sign','mmsi_number','official_number','class_number'].map(k=><Field key={k} name={k} form={form} set={set}/>) }<Pick name="vessel_type_id" title="Vessel Type" form={form} set={set} options={options(types)}/><Pick name="flag_state" title="Flag State" form={form} set={set} options={flagStates.map(f=>({value:f.flag_name,label:f.flag_name}))}/><Pick name="port_of_registry_id" title="Port of Registry" form={form} set={set} options={ports.map(p=>({value:p.id,label:p.port_name}))}/><Pick name="classification_society" title="Classification Society" form={form} set={set} options={societies.map(s=>({value:s.society_name,label:s.society_name}))}/></TabsContent>
 <TabsContent value="management" className="grid md:grid-cols-2 gap-4 mt-5"><Pick name="ownership_mode_id" title="Ownership / Employment Mode" form={form} set={set} options={options(modes)}/><Pick name="owner_company_id" title="Owner" form={form} set={set} options={roles('is_owner')}/><Pick name="operator_company_id" title="Operator" form={form} set={set} options={roles('is_operator')}/><Pick name="technical_manager_id" title="Technical Manager" form={form} set={set} options={roles('is_technical_manager')}/><Pick name="ism_manager_id" title="ISM Manager" form={form} set={set} options={roles('is_ism_manager')}/></TabsContent>
 <TabsContent value="technical" className="grid md:grid-cols-3 gap-4 mt-5">{['gross_tonnage','net_tonnage','deadweight','year_built','length_overall','beam','depth','draft','engine_power','max_speed','service_speed','fuel_consumption','lifeboats','liferafts','crew_capacity','passenger_capacity','cargo_capacity'].map(k=><Field key={k} name={k} form={form} set={set} type="number"/>)}<Pick name="propulsion_type_id" title="Propulsion Type" form={form} set={set} options={options(props)}/><Pick name="fuel_type_id" title="Fuel Type" form={form} set={set} options={options(fuels)}/><Pick name="hull_material_id" title="Hull Material" form={form} set={set} options={options(hulls)}/><Pick name="hull_coating_id" title="Hull Coating" form={form} set={set} options={coatings.map(c=>({value:c.id,label:c.coating_type}))}/><Pick name="trading_area_id" title="Trading Area" form={form} set={set} options={options(areas)}/><Pick name="engine_make" title="Engine Maker" form={form} set={set} options={makers.map(x=>({value:x.maker_name,label:x.maker_name}))}/><Pick name="engine_model" title="Engine Model" form={form} set={set} options={models.map(x=>({value:x.model_name,label:x.model_name}))}/></TabsContent>
 <TabsContent value="operational" className="grid md:grid-cols-3 gap-4 mt-5">{['operational_status','cabin_count','max_speed','service_speed','crew_capacity','passenger_capacity'].map(k=><Field key={k} name={k} form={form} set={set} type={k==='operational_status'?'text':'number'}/>)}<Pick name="vessel_status_id" title="Operational Status" form={form} set={set} options={options(statuses)}/><Pick name="trading_area_id" title="Trading Area" form={form} set={set} options={options(areas)}/><div className="md:col-span-3"><Label>Operational Notes</Label><Textarea value={form.operational_notes||''} onChange={e=>set('operational_notes',e.target.value)}/></div></TabsContent>
 <TabsContent value="financial" className="space-y-5 mt-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Calculator className="h-5 w-5"/>Daily Vessel Baseline</CardTitle></CardHeader><CardContent className="grid md:grid-cols-3 gap-4"><Field name="minimum_daily_hire_rate" form={financial} set={(k,v)=>setFinancial((p:any)=>({...p,[k]:Number(v)}) )} type="number"/><Pick name="currency_code" title="Currency" form={financial} set={(k,v)=>setFinancial((p:any)=>({...p,[k]:v}))} options={currencies.map((c:any)=>({value:c.currency_code,label:`${c.currency_code} — ${c.currency_name||''}`}))}/>{['minimum_charter_period_days',...COST_FIELDS].map(k=><Field key={k} name={k} form={financial} set={(x,v)=>setFinancial((p:any)=>({...p,[x]:Number(v)}))} type="number"/>)}</CardContent></Card><Card><CardHeader><CardTitle>Equipment Daily Costs</CardTitle></CardHeader><CardContent className="space-y-2">{equipment.map((r,i)=><div className="grid grid-cols-[1fr_180px_40px] gap-2" key={r.id||i}><Input placeholder="Equipment" value={r.equipment_name||''} onChange={e=>setEquipment(a=>a.map((x,j)=>j===i?{...x,equipment_name:e.target.value}:x))}/><Input type="number" value={r.daily_cost||0} onChange={e=>setEquipment(a=>a.map((x,j)=>j===i?{...x,daily_cost:Number(e.target.value)}:x))}/><Button size="icon" variant="ghost" onClick={()=>setEquipment(a=>a.filter((_,j)=>j!==i))}><X className="h-4 w-4"/></Button></div>)}<Button variant="outline" onClick={()=>setEquipment(a=>[...a,{equipment_name:'',daily_cost:0,currency_code:financial.currency_code}])}><Plus className="mr-2 h-4 w-4"/>Add Equipment</Button></CardContent></Card><Card><CardHeader><CardTitle>Other Daily Operating Costs</CardTitle></CardHeader><CardContent className="space-y-2">{otherCosts.map((r,i)=><div className="grid grid-cols-[1fr_1fr_160px_40px] gap-2" key={r.id||i}><Input placeholder="Category" value={r.category||''} onChange={e=>setOtherCosts(a=>a.map((x,j)=>j===i?{...x,category:e.target.value}:x))}/><Input placeholder="Description" value={r.description||''} onChange={e=>setOtherCosts(a=>a.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/><Input type="number" value={r.daily_cost||0} onChange={e=>setOtherCosts(a=>a.map((x,j)=>j===i?{...x,daily_cost:Number(e.target.value)}:x))}/><Button size="icon" variant="ghost" onClick={()=>setOtherCosts(a=>a.filter((_,j)=>j!==i))}><X className="h-4 w-4"/></Button></div>)}<Button variant="outline" onClick={()=>setOtherCosts(a=>[...a,{category:'',description:'',daily_cost:0,currency_code:financial.currency_code}])}><Plus className="mr-2 h-4 w-4"/>Add Cost</Button></CardContent></Card><div className="p-5 rounded-xl border font-black flex justify-between"><span>TOTAL DAILY VESSEL OPERATING COST</span><span>{totalDaily.toLocaleString()} {financial.currency_code||''}</span></div></TabsContent>
 <TabsContent value="regularity" className="space-y-4 mt-5">{regularityRows.map((r,i)=><Card key={r.id||i}><CardContent className="grid md:grid-cols-3 gap-4 p-4"><Pick name="regularity_id" title="Regularity" form={r} set={(k,v)=>setRegularityRows(a=>a.map((x,j)=>j===i?{...x,[k]:v}:x))} options={options(regs)}/><Pick name="applicability_status_id" title="Applicability" form={r} set={(k,v)=>setRegularityRows(a=>a.map((x,j)=>j===i?{...x,[k]:v}:x))} options={options(applicability)}/>{['effective_from','effective_to','exemption_reference','exemption_reason','document_reference','notes'].map(k=><div key={k}><Label>{label(k)}</Label><Input type={k.includes('effective_')?'date':'text'} value={r[k]||''} onChange={e=>setRegularityRows(a=>a.map((x,j)=>j===i?{...x,[k]:e.target.value}:x))}/></div>)}<Button variant="ghost" onClick={()=>setRegularityRows(a=>a.filter((_,j)=>j!==i))}><X className="mr-2 h-4 w-4"/>Remove</Button></CardContent></Card>)}<Button variant="outline" onClick={()=>setRegularityRows(a=>[...a,{regularity_id:'',applicability_status_id:'',effective_from:null,effective_to:null,exemption_reference:'',exemption_reason:'',document_reference:'',notes:''}])}><Plus className="mr-2 h-4 w-4"/>Add Regularity</Button></TabsContent>
 <TabsContent value="maintenance" className="grid md:grid-cols-2 gap-4 mt-5"><Field name="keel_laid_date" form={form} set={set} type="date"/><Field name="delivery_date" form={form} set={set} type="date"/><Field name="last_drydock_date" form={form} set={set} type="date"/><Field name="next_drydock_date" form={form} set={set} type="date"/><Pick name="previous_yard" title="Previous Yard" form={form} set={set} options={yards.map(y=>({value:y.yard_name,label:y.yard_name}))}/><Field name="remaining_tasks" form={form} set={set}/><Field name="painting_details" form={form} set={set}/></TabsContent>
 <TabsContent value="media" className="space-y-4 mt-5"><Label>Vessel Brochure / Technical PDF</Label><Input type="file" accept="application/pdf,image/*" onChange={upload}/><Button variant="outline" onClick={smartFill} disabled={!form.vessel_brochure}><Upload className="mr-2 h-4 w-4"/>Run AI Technical Extraction</Button><p className="text-xs text-muted-foreground">Existing Supabase analyze-image pipeline is retained. Unmapped document specifications are preserved.</p></TabsContent>
 <TabsContent value="additional" className="space-y-4 mt-5"><div><Label>Navigation Equipment</Label><Textarea value={form.navigation_equipment||''} onChange={e=>set('navigation_equipment',e.target.value)}/></div><div><Label>Accommodation / Cabin Details</Label><Textarea value={form.accommodations_pax||''} onChange={e=>set('accommodations_pax',e.target.value)}/></div><div><Label>Additional / Unmapped Specifications</Label><Textarea className="min-h-[280px]" value={form.additional_unmapped_specifications||''} onChange={e=>set('additional_unmapped_specifications',e.target.value)}/></div><div><Label>General Notes</Label><Textarea value={form.notes||''} onChange={e=>set('notes',e.target.value)}/></div></TabsContent>
 </Tabs></DialogContent></Dialog></div>
}
