// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-vessels.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function resolveOrgId(client, userId) {
  if (!userId) throw new Error("No authenticated user");
  const { data, error } = await client.from("organization_members").select("org_id").eq("user_id", userId).limit(1).maybeSingle();
  if (error) throw new Error(error.message);
  if (!data?.org_id) throw new Error("This account is not a member of any organization");
  return data.org_id;
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/list-vessels.ts
var list_vessels_default = defineTool({
  name: "list_vessels",
  title: "List vessels",
  description: "List vessels in the signed-in user's organization fleet, optionally filtered by name or IMO number.",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Filter by vessel name or IMO number."),
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum vessels to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const orgId = await resolveOrgId(supabase, ctx.getUserId());
    let query = supabase.from("vessels").select("id, name, imo_number, call_sign, vessel_type, flag_state, classification_society, gross_tonnage, deadweight, year_built, status").eq("org_id", orgId).order("name", { ascending: true }).limit(limit ?? 25);
    if (search) query = query.or(`name.ilike.%${search}%,imo_number.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, vessels: data ?? [] });
  }
});

// src/lib/mcp/tools/get-vessel-profile.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.23.8";
var get_vessel_profile_default = defineTool2({
  name: "get_vessel_profile",
  title: "Get vessel profile",
  description: "Get the full particulars of one vessel plus its certificates, by vessel id or IMO number.",
  inputSchema: {
    vessel_id: z2.string().uuid().optional().describe("Vessel UUID."),
    imo_number: z2.string().trim().min(3).optional().describe("IMO number, used when vessel_id is unknown.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ vessel_id, imo_number }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    if (!vessel_id && !imo_number) return errorResult("Provide either vessel_id or imo_number.");
    const supabase = supabaseForUser(ctx);
    const orgId = await resolveOrgId(supabase, ctx.getUserId());
    let query = supabase.from("vessels").select("*").eq("org_id", orgId).limit(1);
    query = vessel_id ? query.eq("id", vessel_id) : query.eq("imo_number", imo_number);
    const { data: vessel, error } = await query.maybeSingle();
    if (error) return errorResult(error.message);
    if (!vessel) return errorResult("Vessel not found in your organization.");
    const { data: certificates, error: certError } = await supabase.from("vessel_certifications").select("id, certificate_name, certificate_type, issuing_authority, issue_date, expiry_date, status").eq("vessel_id", vessel.id).order("expiry_date", { ascending: true });
    if (certError) return errorResult(certError.message);
    return jsonResult({ vessel, certificates: certificates ?? [] });
  }
});

// src/lib/mcp/tools/list-expiring-certificates.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.23.8";
var list_expiring_certificates_default = defineTool3({
  name: "list_expiring_certificates",
  title: "List expiring certificates",
  description: "List statutory and class certificates in the fleet that expire within a given number of days.",
  inputSchema: {
    within_days: z3.number().int().min(1).max(365).default(90).describe("Look-ahead window in days."),
    vessel_id: z3.string().uuid().optional().describe("Restrict to a single vessel."),
    limit: z3.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ within_days, vessel_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const orgId = await resolveOrgId(supabase, ctx.getUserId());
    const { data: vessels, error: vesselError } = await supabase.from("vessels").select("id, name, imo_number").eq("org_id", orgId);
    if (vesselError) return errorResult(vesselError.message);
    const fleet = vessels ?? [];
    const ids = fleet.filter((v) => !vessel_id || v.id === vessel_id).map((v) => v.id);
    if (ids.length === 0) return jsonResult({ count: 0, certificates: [] });
    const cutoff = new Date(Date.now() + (within_days ?? 90) * 864e5).toISOString().slice(0, 10);
    const { data, error } = await supabase.from("vessel_certifications").select("id, vessel_id, certificate_name, certificate_type, issuing_authority, expiry_date, status").in("vessel_id", ids).lte("expiry_date", cutoff).order("expiry_date", { ascending: true }).limit(limit ?? 50);
    if (error) return errorResult(error.message);
    const byId = new Map(fleet.map((v) => [v.id, v]));
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const certificates = (data ?? []).map((c) => {
      const row = c;
      const vessel = row.vessel_id ? byId.get(row.vessel_id) : void 0;
      return {
        ...c,
        vessel_name: vessel?.name ?? null,
        imo_number: vessel?.imo_number ?? null,
        expired: row.expiry_date < today
      };
    });
    return jsonResult({ count: certificates.length, within_days: within_days ?? 90, certificates });
  }
});

// src/lib/mcp/tools/list-incidents.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.23.8";
var list_incidents_default = defineTool4({
  name: "list_incidents",
  title: "List incidents",
  description: "List reported safety, pollution and near-miss incidents for the organization's fleet.",
  inputSchema: {
    vessel_id: z4.string().uuid().optional().describe("Restrict to a single vessel."),
    severity: z4.enum(["low", "medium", "high", "critical"]).optional().describe("Filter by severity."),
    since: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Only incidents on or after this date (YYYY-MM-DD)."),
    limit: z4.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ vessel_id, severity, since, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const orgId = await resolveOrgId(supabase, ctx.getUserId());
    let query = supabase.from("incidents").select("id, title, incident_type, severity, incident_date, location, investigation_status, vessel_id, vessels(name)").eq("org_id", orgId).order("incident_date", { ascending: false }).limit(limit ?? 25);
    if (vessel_id) query = query.eq("vessel_id", vessel_id);
    if (severity) query = query.eq("severity", severity);
    if (since) query = query.gte("incident_date", since);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, incidents: data ?? [] });
  }
});

// src/lib/mcp/tools/report-incident.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.23.8";
var report_incident_default = defineTool5({
  name: "report_incident",
  title: "Report an incident",
  description: "Create a new incident record (safety, pollution, near-miss) for a vessel in the organization.",
  inputSchema: {
    title: z5.string().trim().min(3).max(200).describe("Short incident title."),
    incident_type: z5.string().trim().min(2).max(100).describe("Incident type, e.g. Near Miss, Injury, Pollution."),
    incident_date: z5.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Date of the incident (YYYY-MM-DD)."),
    severity: z5.enum(["low", "medium", "high", "critical"]).default("low"),
    vessel_id: z5.string().uuid().optional().describe("Vessel involved."),
    location: z5.string().trim().max(200).optional().describe("Position or port where it happened."),
    description: z5.string().trim().max(4e3).optional().describe("What happened.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const orgId = await resolveOrgId(supabase, userId);
    if (input.vessel_id) {
      const { data: vessel, error: vesselError } = await supabase.from("vessels").select("id").eq("org_id", orgId).eq("id", input.vessel_id).maybeSingle();
      if (vesselError) return errorResult(vesselError.message);
      if (!vessel) return errorResult("Vessel not found in your organization.");
    }
    const { data, error } = await supabase.from("incidents").insert({
      org_id: orgId,
      user_id: userId,
      title: input.title,
      incident_type: input.incident_type,
      incident_date: input.incident_date,
      severity: input.severity,
      vessel_id: input.vessel_id ?? null,
      location: input.location ?? null,
      description: input.description ?? null,
      investigation_status: "open"
    }).select("id, title, incident_type, severity, incident_date, investigation_status").single();
    if (error) return errorResult(error.message);
    return jsonResult({ created: data });
  }
});

// src/lib/mcp/tools/list-audit-findings.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.23.8";
var list_audit_findings_default = defineTool6({
  name: "list_audit_findings",
  title: "List audit findings",
  description: "List audit findings (non-conformities, observations) raised across the organization's audits.",
  inputSchema: {
    vessel_id: z6.string().uuid().optional().describe("Restrict to findings from audits on this vessel."),
    status: z6.string().trim().min(1).optional().describe("Filter by finding status, e.g. open or closed."),
    limit: z6.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ vessel_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const orgId = await resolveOrgId(supabase, ctx.getUserId());
    let query = supabase.from("audit_findings").select("*, audits!inner(org_id, vessel_id, audit_type, audit_date)").eq("audits.org_id", orgId).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (vessel_id) query = query.eq("audits.vessel_id", vessel_id);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, findings: data ?? [] });
  }
});

// src/lib/mcp/tools/fleet-compliance-summary.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
var fleet_compliance_summary_default = defineTool7({
  name: "fleet_compliance_summary",
  title: "Fleet compliance summary",
  description: "Summarize fleet compliance: vessel count, certificates expired or expiring within 90 days, and open incidents.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const orgId = await resolveOrgId(supabase, ctx.getUserId());
    const { data: vessels, error: vesselError } = await supabase.from("vessels").select("id, name, status").eq("org_id", orgId);
    if (vesselError) return errorResult(vesselError.message);
    const fleet = vessels ?? [];
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const soon = new Date(Date.now() + 90 * 864e5).toISOString().slice(0, 10);
    let expired = 0;
    let expiringSoon = 0;
    if (fleet.length > 0) {
      const { data: certs, error: certError } = await supabase.from("vessel_certifications").select("expiry_date").in("vessel_id", fleet.map((v) => v.id)).lte("expiry_date", soon);
      if (certError) return errorResult(certError.message);
      for (const c of certs ?? []) {
        if (c.expiry_date < today) expired += 1;
        else expiringSoon += 1;
      }
    }
    const { data: incidents, error: incidentError } = await supabase.from("incidents").select("severity, investigation_status").eq("org_id", orgId);
    if (incidentError) return errorResult(incidentError.message);
    const rows = incidents ?? [];
    return jsonResult({
      vessels: {
        total: fleet.length,
        active: fleet.filter((v) => (v.status ?? "").toLowerCase() === "active").length
      },
      certificates: { expired, expiring_within_90_days: expiringSoon },
      incidents: {
        total: rows.length,
        open: rows.filter((i) => (i.investigation_status ?? "open").toLowerCase() !== "closed").length,
        high_or_critical: rows.filter((i) => ["high", "critical"].includes((i.severity ?? "").toLowerCase())).length
      }
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "jpggwhyabwettgwgktdm";
var mcp_default = defineMcp({
  name: "eagle-maritime-cog-os",
  title: "Eagle-Maritime COG. OS",
  version: "0.1.0",
  instructions: "Tools for Eagle Maritime OS, a vessel compliance and fleet management platform. Use `fleet_compliance_summary` for a quick fleet health check, `list_vessels` and `get_vessel_profile` for vessel particulars and certificates, `list_expiring_certificates` for statutory/class certificate renewals, `list_audit_findings` for ISM/ISPS audit non-conformities, and `list_incidents` / `report_incident` for incident management. All data is scoped to the signed-in user's organization.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    fleet_compliance_summary_default,
    list_vessels_default,
    get_vessel_profile_default,
    list_expiring_certificates_default,
    list_audit_findings_default,
    list_incidents_default,
    report_incident_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
