REVOKE USAGE ON SCHEMA graphql FROM PUBLIC;
REVOKE USAGE ON SCHEMA graphql_public FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA graphql_public FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA graphql FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA graphql FROM PUBLIC;